-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 21:00:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `sistema_pizzaria` ;

-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_endereco_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_endereco_entrega` (
  `id_endereco_entrega` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(150) NOT NULL,
  `rua` VARCHAR(150) NOT NULL,
  `numero` INT NULL,
  PRIMARY KEY (`id_endereco_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `id_endereco_entrega` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_tb_clientes_tb_endereco_entrega1_idx` (`id_endereco_entrega` ASC) VISIBLE,
  CONSTRAINT `fk_tb_clientes_tb_endereco_entrega1`
    FOREIGN KEY (`id_endereco_entrega`)
    REFERENCES `sistema_pizzaria`.`tb_endereco_entrega` (`id_endereco_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_pizzas` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `ingredientes` VARCHAR(255) NULL,
  `preco` DECIMAL NULL,
  `disponibilidade` VARCHAR(20) NULL,
  PRIMARY KEY (`id_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_bebidas` (
  `id_bebida` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `preco` DECIMAL NULL,
  `disponibilidade` VARCHAR(20) NULL,
  PRIMARY KEY (`id_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_cardapio` (
  `id_cardapio` INT NOT NULL AUTO_INCREMENT,
  `id_pizza` INT NOT NULL,
  `id_bebida` INT NOT NULL,
  PRIMARY KEY (`id_cardapio`),
  INDEX `fk_tb_cardapio_tb_pizzas_idx` (`id_pizza` ASC) VISIBLE,
  INDEX `fk_tb_cardapio_tb_bebidas1_idx` (`id_bebida` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cardapio_tb_pizzas`
    FOREIGN KEY (`id_pizza`)
    REFERENCES `sistema_pizzaria`.`tb_pizzas` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cardapio_tb_bebidas1`
    FOREIGN KEY (`id_bebida`)
    REFERENCES `sistema_pizzaria`.`tb_bebidas` (`id_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_itens_pedido` (
  `id_itens_pedido` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL NOT NULL,
  `id_pizza` INT NOT NULL,
  `id_bebida` INT NOT NULL,
  PRIMARY KEY (`id_itens_pedido`, `id_pizza`, `id_bebida`),
  INDEX `fk_tb_itens_pedido_tb_pizzas1_idx` (`id_pizza` ASC) VISIBLE,
  INDEX `fk_tb_itens_pedido_tb_bebidas1_idx` (`id_bebida` ASC) VISIBLE,
  CONSTRAINT `fk_tb_itens_pedido_tb_pizzas1`
    FOREIGN KEY (`id_pizza`)
    REFERENCES `sistema_pizzaria`.`tb_pizzas` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_itens_pedido_tb_bebidas1`
    FOREIGN KEY (`id_bebida`)
    REFERENCES `sistema_pizzaria`.`tb_bebidas` (`id_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_motoboys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_motoboys` (
  `id_motoboy` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `disponibilidade` VARCHAR(20) NULL,
  PRIMARY KEY (`id_motoboy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` VARCHAR(50) NULL,
  `data` VARCHAR(20) NULL,
  `id_itens_pedido` INT NOT NULL,
  `id_endereco_entrega` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_motoboy` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_tb_pedidos_tb_itens_pedido1_idx` (`id_itens_pedido` ASC) VISIBLE,
  INDEX `fk_tb_pedidos_tb_endereco_entrega1_idx` (`id_endereco_entrega` ASC) VISIBLE,
  INDEX `fk_tb_pedidos_tb_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_tb_pedidos_tb_motoboys1_idx` (`id_motoboy` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedidos_tb_itens_pedido1`
    FOREIGN KEY (`id_itens_pedido`)
    REFERENCES `sistema_pizzaria`.`tb_itens_pedido` (`id_itens_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedidos_tb_endereco_entrega1`
    FOREIGN KEY (`id_endereco_entrega`)
    REFERENCES `sistema_pizzaria`.`tb_endereco_entrega` (`id_endereco_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedidos_tb_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_pizzaria`.`tb_clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedidos_tb_motoboys1`
    FOREIGN KEY (`id_motoboy`)
    REFERENCES `sistema_pizzaria`.`tb_motoboys` (`id_motoboy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_pizzaria`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pizzaria`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuarios_tb_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuarios_tb_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `sistema_pizzaria`.`tb_clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
